### ISSUE TITLE
[Docker] Add Healthcheck to containers

### ISSUE THREAD

**Issue by Zitrone44** [thm-mni-ii/feedbacksystem#700]
Health checks for all containers should be added to the `docker-compose.yml`.

Example:

  ```yml
  healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 10s
        retries: 10
  ```
